# Generated by Django 2.1.2 on 2018-11-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='html',
        ),
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='job',
            name='views',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
