# Generated by Django 2.1.2 on 2018-11-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181110_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
