# Generated by Django 2.1.2 on 2018-11-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181119_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-last_modified',), 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
