# Generated by Django 2.1.2 on 2018-11-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20181119_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
