# Generated by Django 2.1.2 on 2018-11-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20181110_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=2, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
