# Generated by Django 2.1.2 on 2018-11-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20181110_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='job',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
    ]
