# Generated by Django 2.1.1 on 2018-11-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20181119_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
