# Generated by Django 2.1.1 on 2018-11-20 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='worker_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jobWorker', to=settings.AUTH_USER_MODEL),
        ),
    ]
