# Generated by Django 2.1.1 on 2018-11-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20181120_0227'),
        ('jobs', '0007_job_image'),
    ]

    operations = [
    ]
