# Generated by Django 2.1.2 on 2018-11-20 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobinterested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobInterested', to='jobs.Job')),
                ('worker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jobInterestedWorker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
