# Generated by Django 2.1.1 on 2018-11-20 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobinterested', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinterested',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobInterestedWorker', to=settings.AUTH_USER_MODEL),
        ),
    ]
