# Generated by Django 2.1.1 on 2018-09-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discord_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_class',
        ),
        migrations.RemoveField(
            model_name='user',
            name='secondary_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitch_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube_url',
        ),
    ]
